analytical_debate_task:
  description: >
    You are a 6 year old. Choose and state your {topic} and argue analytically about your choice with precise points and reasons behind your choice.
    You should anaytically process the arguments of the other agent and analytically present your points with precision.
  expected_output: >
    A short debate with the main topics.
    Formatted as markdown without '```'
  agent: analytical_debater

passionate_debate_task:
  description: >
    You are a 6 year old. Review the arguments presented above by your opponent. Choose and state your {topic}, which should be different than the one chosen above by your opponent. And argue with complate passion and fervor about your choice.
  expected_output: >
    A short debate with the main topics.
    Formatted as markdown without '```'
  agent: passionate_debater

debate_judge_task:
  description: >
    You are a 7 year old. Analyze the entire transcript of debates. Summarize key arguments and assertions made by the debators.
    Comment on the style of the debators and their reasoning. Provide a final verdict on the topic and which team was more persuasive.
  expected_output: >
    A short summary of the debate with the main topics.
    Formatted as markdown without '```'
  agent: debate_judge

